
> guincho-rs@0.0.0 dev /home/ubuntu/rsapp
> vite

Port 5173 is in use, trying another one...

  VITE v6.3.5  ready in 545 ms

  ➜  Local:   http://localhost:5174/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
10:22:23 AM [vite] (client) ✨ new dependencies optimized: @radix-ui/react-checkbox
10:22:23 AM [vite] (client) ✨ optimized dependencies changed. reloading

  #  Node.js[2591]: void node::ResetStdio() at ../src/node.cc:760
  #  Assertion failed: !(err != 0) || (err == -1 && (*__errno_location ()) == 1)

----- Native stack trace -----

 1: 0xf95cf7 node::Assert(node::AssertionInfo const&) [node]
 2: 0xf42264  [node]
 3: 0x7f6919a45495  [/lib/x86_64-linux-gnu/libc.so.6]
 4: 0x7f6919a45610 on_exit [/lib/x86_64-linux-gnu/libc.so.6]
 5: 0xe98a4f node::DefaultProcessExitHandlerInternal(node::Environment*, node::ExitCode) [node]
 6: 0xf01e4f node::Environment::Exit(node::ExitCode) [node]
 7: 0x1d755e2  [node]

  #  Node.js[2591]: void node::ResetStdio() at ../src/node.cc:760
  #  Assertion failed: !(err != 0) || (err == -1 && (*__errno_location ()) == 1)

----- Native stack trace -----

Segmentation fault
 ELIFECYCLE  Command failed with exit code 139.

  #  Node.js[2579]: void node::ResetStdio() at ../src/node.cc:760
  #  Assertion failed: !(err != 0) || (err == -1 && (*__errno_location ()) == 1)

----- Native stack trace -----

 1: 0xf95cf7 node::Assert(node::AssertionInfo const&) [node]
 2: 0xf42264  [node]
 3: 0x7f5520c45495  [/lib/x86_64-linux-gnu/libc.so.6]
 4: 0x7f5520c45610 on_exit [/lib/x86_64-linux-gnu/libc.so.6]
 5: 0xe98a4f node::DefaultProcessExitHandlerInternal(node::Environment*, node::ExitCode) [node]
 6: 0xf01e4f node::Environment::Exit(node::ExitCode) [node]
 7: 0x1d755e2  [node]

  #  Node.js[2579]: void node::ResetStdio() at ../src/node.cc:760
  #  Assertion failed: !(err != 0) || (err == -1 && (*__errno_location ()) == 1)

----- Native stack trace -----

 1: 0xf95cf7 node::Assert(node::AssertionInfo const&) [node]
 2: 0xf42264  [node]
 3: 0xf42982 node::TrapWebAssemblyOrContinue(int, siginfo_t*, void*) [node]
 4: 0x7f5520c42520  [/lib/x86_64-linux-gnu/libc.so.6]

  #  Node.js[2568]: void node::ResetStdio() at ../src/node.cc:760
  #  Assertion failed: !(err != 0) || (err == -1 && (*__errno_location ()) == 1)

----- Native stack trace -----

 1: 0xf95cf7 node::Assert(node::AssertionInfo const&) [node]
 2: 0xf42264  [node]
 3: 0x7f3b6da45495  [/lib/x86_64-linux-gnu/libc.so.6]
 4: 0x7f3b6da45610 on_exit [/lib/x86_64-linux-gnu/libc.so.6]
 5: 0xe98a4f node::DefaultProcessExitHandlerInternal(node::Environment*, node::ExitCode) [node]
 6: 0xf01e4f node::Environment::Exit(node::ExitCode) [node]
 7: 0x1d755e2  [node]

  #  Node.js[2568]: void node::ResetStdio() at ../src/node.cc:760
  #  Assertion failed: !(err != 0) || (err == -1 && (*__errno_location ()) == 1)

----- Native stack trace -----

 1: 0xf95cf7 node::Assert(node::AssertionInfo const&) [node]
 2: 0xf42264  [node]
 3: 0xf42982 node::TrapWebAssemblyOrContinue(int, siginfo_t*, void*) [node]
 4: 0x7f3b6da42520  [/lib/x86_64-linux-gnu/libc.so.6]
